### ISSUE TITLE
GO-stats: refactor code

### ISSUE THREAD

**Issue by lpalbou** [geneontology/go-stats#12]
Put utility functions shared by multiple scripts in a single go_stats_utils.py file. This will simplify the code and help some future refactoring if/when needed.

**Comment by kltm** [comment]
I'm not sure what the best place to put this would be, but as part of a refactor, we'll be wanting to move away from (or more efficiently and scaleably use) eUtils: https://github.com/geneontology/pipeline/issues/173 . IIRC, @goodb had an idea around this as well. Would this be better as another ticket here? Or maybe I can just move the pipeline ticket over (and delete this comment)?

**Comment by lpalbou** [comment]
That's not the intent of this refactor. Some codes (like read/write file/json, and methods to manipulate map & set etc) were duplicated/spread in go_stats, go_reports go_refine etc. They have just been merged into go_stats_utils.py to ease the maintenance and readability.

As for the eutils you mentioned in https://github.com/geneontology/pipeline/issues/173, there is 1 remote call at the beginning of the stats process but for the stats, it already has a fallback to another API. I suggest we keep track of other possible solution for eutils in the original ticket, I will be closing this one when the stats are merged to the pipeline.

**Comment by kltm** [comment]
:+1:

**Comment by pgaudet** [comment]
@lpalbou Is this still valid?

**Comment by lpalbou** [comment]
Yes this was done: https://github.com/geneontology/go-stats/blob/master/libraries/go-stats/go_stats_utils.py
Closing
