### ISSUE TITLE
Technical planning: Handover of go-stats

### ISSUE THREAD

**Issue by lpalbou** [geneontology/go-stats#17]
* published last release of go-stats on pypi
* tag @dustine32 to update the Jenkins file to install go-stats & launch it from there
* @balhoff just FYI :)

**Comment by kltm** [comment]
@dustine32 to check on ownership of distribution
@kltm to start install if no motion by Monday (next week)

**Comment by kltm** [comment]
@dustine32 We've passed release with the new go-stats setup, so we're technically clear here; we can deal with a pypi release as a separate issue then, or we you could just sign off that you have control here: https://github.com/geneontology/go-stats/issues/17#issuecomment-902232837

**Comment by dustine32** [comment]
@kltm Thanks! Sounds like @lpalbou would like us to publish the go-stats code to PyPI under a different account and new library name, preferably an org account similar to "geneontology" in `npm`. However, I don't think org/group accounts exist in PyPI. I can just make a new PyPI lib, but any suggestions for the new name?

**Comment by lpalbou** [comment]
I do have the possibility to add you to my personal PyPI account.. but it would probably be better just to create a geneontology PyPI account and invite developers ? @cmungall

**Comment by kltm** [comment]
From talking to @dustine32 I think it would be good to just start "clean". For now anyways, we're using the repo method, so we can follow up at our leisure.
